### ISSUE TITLE
Example won't run `no module named 'example'`

### ISSUE THREAD

**Issue by monneyboi** [alephdata/funes#201]
I ran into this problem when my own scraper image that's based of of the `alephdata/memorious` image suddenly started reporting missing modules, while i didn't change any logic.

To make sure i wasn't going crazy i decided to try running the example, which reports the same errors. Any idea what's going on?
```
$> cd example
$> docker-compose run --rm shell
[+] Running 2/0
 ⠿ Container example-redis-1      Running                                                                                                       0.0s
 ⠿ Container example-datastore-1  Running                                                                                                       0.0s
Sending build context to Docker daemon  4.833kB
Step 1/6 : FROM alephdata/memorious:latest
latest: Pulling from alephdata/memorious
Digest: sha256:8495471ab9323044d49fb5c0647b32cb4211f567525fe28bd2a130e1e54bb9e2
Status: Downloaded newer image for alephdata/memorious:latest
 ---> f528901c9f71
Step 2/6 : COPY setup.py /crawlers/
 ---> ec5ab9ddf211
Step 3/6 : COPY src /crawlers/src
 ---> 85abfae3fbbb
Step 4/6 : RUN pip3 install -q -e /crawlers
 ---> Running in 52b3f0c5eefa
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Removing intermediate container 52b3f0c5eefa
 ---> 859bf88f0293
Step 5/6 : COPY config /crawlers/config
 ---> 86c650b9170d
Step 6/6 : ENV MEMORIOUS_BASE_PATH=/data     MEMORIOUS_CONFIG_PATH=/crawlers/config     MEMORIOUS_DEBUG=false     ARCHIVE_PATH=/data/archive     REDIS_URL=redis://redis:6379/0     MEMORIOUS_DATASTORE_URI=postgresql://datastore:datastore@datastore/datastore
 ---> Running in 0ed32956bcb6
Removing intermediate container 0ed32956bcb6
 ---> 74aa084016d8
Successfully built 74aa084016d8
Successfully tagged example_shell:latest


root@287de17909ab:/memorious# memorious run quote_scraper
2022-03-03 15:54:53.119249 [info     ] [quote_scraper->init(example.quotes:login)]: aa697c2552724a8f8c5f35d68c1c680d [quote_scraper.init]
2022-03-03 15:54:53.813445 [error    ] No module named 'example'      [quote_scraper.init]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/memorious/logic/context.py", line 93, in execute
    return self.stage.method(self, data)
  File "/usr/local/lib/python3.8/dist-packages/memorious/logic/stage.py", line 30, in method
    module = import_module(package)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'example'
2022-03-03 15:54:53.814479 [warning  ] Queue failed task for re-try... [servicelayer.worker]
2022-03-03 15:54:53.814986 [error    ] Error in task handling         [servicelayer.worker]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/servicelayer/worker.py", line 40, in handle_safe
    self.handle(task)
  File "/usr/local/lib/python3.8/dist-packages/memorious/worker.py", line 20, in handle
    context.execute(data)
  File "/usr/local/lib/python3.8/dist-packages/memorious/logic/context.py", line 99, in execute
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/memorious/logic/context.py", line 93, in execute
    return self.stage.method(self, data)
  File "/usr/local/lib/python3.8/dist-packages/memorious/logic/stage.py", line 30, in method
    module = import_module(package)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'example'
```

**Comment by monneyboi** [comment]
This is something related to my system, as my coworker can run this perfectly.

**Comment by monneyboi** [comment]
If you also run into this:

Everything works again after adding `PYTHONPATH: /crawlers/src` to the shell container environment. Though my collegues stack is running fine without that environment variable. I still don't really understand what's going on, which annoys me, but this got things running again.

**Comment by rhiaro** [comment]
Thanks, I just ran into this too.
